#pragma once
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <malloc.h>
#include <string.h>
#include <locale.h>
#include "struct.h"
#include "sort.h"
#include "stack_actions.h"
#include "memory.h"
#include "find_word_to_replace.h"
#include "compress_file.h"
#include "clear_word.h"