#pragma once
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <malloc.h>
#include <string.h>
#include <locale.h>
#include "struct.h"
#include "uncompressig_file.h"
#include "clear_word.h"
#include "words_to_replace.h"